In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("/content/drive/MyDrive/Concept and Technologies of AI/Week7/student.csv")
dataset.head()



Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [3]:
# math = dataset['Math']
# read = dataset['Reading']

#using loop

# cols = []
# columns = dataset.columns
# for i in range(len(columns)-1):
#   cols.append(columns[i])

# X = dataset[cols].to_numpy()

#using slicing

X = dataset.iloc[:, :-1].to_numpy()  # select [allrows, allcolumns except last]

print(X)




[[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]


In [5]:
write = dataset["Writing"]

Y = write.to_numpy()
print(Y)

[ 63  72  78  79  62  85  83  41  80  77  64  90  45  77  70  46  76  44
  85  72  53  66  75  49  84  83  68  66  77  78  74  83  72  65  46  66
  50  79  68  46  86  70  61  53  72  75  50  77 100  81 100  87  78  48
  50  44  48  43  67  78  58  91  92  78  42  85  73  83  61  58  60  55
  48  62  68  59  62  48  74  63  80  79  73  79  45  67  89  77  81  88
  53  68  79  77  63  73  60  67 100  79  26  51  80  57  41  78  68  49
  76  41  71  77  89  86  55  80  56  74  85  80  73  74  86  56  53  44
  41  59  71  81  74  78  67  53  56  75  82  79  99  76  59  96  75  61
  56  88  65 100  79  55  61  83  74  59  54  47  82  74  59  74  84  59
  43  65  61  78  84  73  73  92  63  72  61  59  70  87  78  65  73  62
  69  55  73  63  67  86  78  85  83  80  60  90  56  70  55  80  82  60
  78  76  94  75  68  71  85  46  58  46  84  58  57  59  77  63  68  99
  48  91  57  80  46  75  59  87  82  79  66  68  66  61  66  63  72  73
  77  84  83  42  72  76  76  39  74  43  63  74  5

In [ ]:
print(X.shape)
print(Y.shape)

(1000, 2)
(1000,)


In [19]:
W = np.array([0,0,0])
print(W)

[0 0 0]


In [20]:
#updating X because  y = w0 + w1x1 +w2x2 ... >>  in first term there is no x so that
X = np.insert(X,0, 1, axis =1);  # (array, index, value, column) >>inserting value
print(X)

[[ 1 48 68]
 [ 1 62 81]
 [ 1 79 80]
 ...
 [ 1 89 87]
 [ 1 83 82]
 [ 1 66 66]]


In [15]:
#cost function
# the cost function
def cost_function(X, Y, W):
    """ Parameters:
    This function finds the Mean Square Error.
    Input parameters:
      X: Feature Matrix
      Y: Target Matrix
      W: Weight Matrix
    Output Parameters:
      J: accumulated mean square error.
    """
    # Your code here:
    m = len(Y)
    h_thita = np.dot(X,W)     # were W can be thita
    err = h_thita - Y
    J = (1/(2*m))* np.sum(err ** 2 )  # where J is cost function


    return J

In [21]:
#passing the values
inital_cost = cost_function(X, Y, W)
print(inital_cost)

2470.11


In [29]:
# Gradient descent
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)

    for iteration in range(iterations):
        # Hypothesis Values
        Y_pred = X.dot(W)
        # Difference b/w Hypothesis and Actual Y
        loss = Y_pred - Y
        # Gradient Calculation
        dw = X.T.dot(loss) / m
        # Changing Values of B using Gradient
        W_update = W - alpha * dw
        # New Cost Value
        cost = cost_function(X, Y, W_update)
        cost_history[iteration] = cost



    return W_update, cost_history

In [30]:
# 100000 Iterations
alpha = 0.0001 # Learning Rate.
new_weights, cost_history = gradient_descent(X, Y, W, alpha, 100000)

# New Values of
print(new_weights)

# Final Cost of our Iterations.
print(cost_history[-1])

[0.0068616 0.4801185 0.5006844]
18.076027940915417


In [34]:
#Model Evaluation

# Model Evaluation - RMSE
def rmse(Y, Y_pred):
  """
  This Function calculates the Root Mean Squres.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rmse: Root Mean Square.
  """
  m = len(Y)
  mse = np.sum((Y-Y_pred)**2)/m
  rmse = np.sqrt(mse)
  return rmse

# Model Evaluation - R2

def r2(Y, Y_pred):
  """
   This Function calculates the R Squared Error.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rsquared: R Squared Error.
    """
  mean_y = np.mean(Y)
  ss_tot = np.sum((Y - mean_y) ** 2)
  ss_res = np.sum((Y -Y_pred) ** 2)
  r2 = 1 - (ss_res/ ss_tot)
  return r2


In [39]:
#checking model performance
Y_pred = X.dot(new_weights)
print(X)
print(rmse(Y, Y_pred))
print(r2(Y, Y_pred))

[[ 1 48 68]
 [ 1 62 81]
 [ 1 79 80]
 ...
 [ 1 89 87]
 [ 1 83 82]
 [ 1 66 66]]
6.012657971465767
0.8442155132417348


In [43]:
#for my predection of new values
C = np.array([[48,68],[50,55],[42,64],[59,64]])
C = np.insert(C,0,1,axis=1)
new_Y_pred = C.dot(new_weights)
print(new_Y_pred)

[57.0990888 51.5504286 52.2156402 60.3776547]
